lib/visions_unite_web/router.ex
defmodule VisionsUniteWeb.Router do
  use VisionsUniteWeb, :router

  import VisionsUniteWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VisionsUniteWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :user_session do
    plug VisionsUniteWeb.UserSessionPlug
  end

  scope "/", VisionsUniteWeb do
    pipe_through [:browser, :user_session]

    live "/", FullySupportedExpressionsLive.Index, :index_important_groups
    live "/important_groups", FullySupportedExpressionsLive.Index, :index_important_groups
    live "/important_messages", FullySupportedExpressionsLive.Index, :index_important_messages

    get "/about", PageController, :about
    post "/about", PageController, :update_about
  end

  # Other scopes may use custom stacks.
  # scope "/api", VisionsUniteWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: VisionsUniteWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", VisionsUniteWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", VisionsUniteWeb do
    pipe_through [:browser, :require_authenticated_user, :user_session]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    post "/create_expressions", PageController, :create_expression
    post "/submit_vote", PageController, :submit_vote

    get "/vote", PageController, :vote

    post "/save_group", PageController, :save_group
    post "/save_message", PageController, :save_message

    live "/expression/:id/new", ExpressionShowLive.Show, :new

    live "/my_expressions", MyExpressionsLive.Index, :index
    live "/my_expressions/new", MyExpressionsLive.Index, :new

    live "/my_subscribed_groups", FullySupportedExpressionsLive.Index, :my_subscribed_groups
    live "/my_subscribed_messages", FullySupportedExpressionsLive.Index, :my_subscribed_messages

    live "/all_expressions", AllExpressionsLive.Index, :index
  end

  scope "/", VisionsUniteWeb do
    pipe_through [:browser, :user_session]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update

    live "/expression/:id", ExpressionShowLive.Show, :show
  end
end

lib/visions_unite_web/live/expression_live/expression_component.ex
defmodule VisionsUniteWeb.ExpressionComponent do
  use VisionsUniteWeb, :live_view
  use Phoenix.Component

  def render(assigns) do
    expression(assigns)
  end

  def expression(assigns) do
    ~H"""
    <p>
      <%= if is_list(@expression.fully_supporteds) and Enum.count(@expression.fully_supporteds) !== 0 do %>
        <%= link to: "/expression/#{@expression.id}" do %>
          <b>
            / <%= Enum.join(@expression.fully_supporteds, ", ") %> / <%= @expression.title %>
          </b>
        <% end %>
      <% else %>
        <%= link to: "/expression/#{@expression.id}" do %>
          <b>
            / <%= @expression.title %>
          </b>
        <% end %>
      <% end %>
    </p>
    """
  end
end

lib/visions_unite_web/live/expression_live/form_component.ex
defmodule VisionsUniteWeb.ExpressionLive.FormComponent do
  use VisionsUniteWeb, :live_component

  alias VisionsUnite.Expressions

  @impl true
  def update(%{expression: expression} = assigns, socket) do
    changeset = Expressions.change_expression(expression)

    socket =
      socket
      |> assign(assigns)
      |> assign(:changeset, changeset)

    {:ok, socket}
  end

  @impl true
  def handle_event("validate", %{"expression" => expression_params}, socket) do
    changeset =
      socket.assigns.expression
      |> Expressions.change_expression(expression_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save_group", %{"expression" => expression_params}, socket) do
    expression_params = Map.put(expression_params, "author_id", socket.assigns.current_user_id)

    case Expressions.create_expression(expression_params) do
      {:ok, _expression, _seeking_supports} ->
        {:noreply,
         socket
         |> put_flash(:info, "Group created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end

  def handle_event("save_message", %{"expression" => expression_params}, socket) do
    expression_params = Map.put(expression_params, "author_id", socket.assigns.current_user_id)
    linked_expressions = [expression_params["linked_expression_id"]]

    case Expressions.create_expression(expression_params, linked_expressions) do
      {:ok, _expression, _seeking_supports} ->
        {:noreply,
         socket
         |> put_flash(:info, "Message created successfully")
         |> push_redirect(to: "/expression/#{expression_params["linked_expression_id"]}")}

      {:error, changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/visions_unite_web/live/expression_show_live/show.ex
defmodule VisionsUniteWeb.ExpressionShowLive.Show do
  use VisionsUniteWeb, :live_view

  alias VisionsUnite.Accounts
  alias VisionsUnite.Supports
  alias VisionsUnite.FullySupporteds
  alias VisionsUnite.SeekingSupports
  alias VisionsUnite.ExpressionLinkages
  alias VisionsUnite.ExpressionSubscriptions
  alias VisionsUnite.Expressions
  alias VisionsUnite.Expressions.Expression
  alias VisionsUniteWeb.ExpressionComponent

  @impl true
  def mount(params, session, socket) do
    user_id = session["current_user_id"]
    expression_id = params["id"]

    socket =
      socket
      |> assign(:view_all, false)
      |> update_expression(expression_id, user_id)

    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :show, _params) do
    socket
    |> assign(:page_title, "Showing Expression")
  end

  defp apply_action(socket, :new, %{"id" => linked_expression_id}) do
    linked_expression_title = Expressions.get_expression!(linked_expression_id).title

    socket
    |> assign(:page_title, "New Message")
    |> assign(:new_expression, %Expression{})
    |> assign(:linked_expression_id, linked_expression_id)
    |> assign(:linked_expression_title, linked_expression_title)
  end

  @impl true
  def handle_event("view_all_toggle", _params, socket) do
    socket =
      socket
      |> assign(:view_all, !socket.assigns.view_all)
      |> update_expression(socket.assigns.expression.id, socket.assigns.current_user_id)

    {:noreply, socket}
  end

  def handle_event("set_follow", %{"expression_id" => expression_id, "follow" => follow}, socket) do
    user_id = socket.assigns.current_user_id

    existing_subscription =
      ExpressionSubscriptions.get_expression_subscription_for_expression_and_user(
        expression_id,
        user_id
      )

    existing_mute =
      ExpressionSubscriptions.get_expression_muting_for_expression_and_user(
        expression_id,
        user_id
      )

    case {existing_subscription, existing_mute} do
      {nil, nil} ->
        ExpressionSubscriptions.create_expression_subscription(%{
          expression_id: expression_id,
          user_id: user_id,
          subscribe: follow
        })

      {existing_subscription, nil} ->
        ExpressionSubscriptions.update_expression_subscription(
          existing_subscription,
          %{
            subscribe: follow
          }
        )

      {nil, existing_mute} ->
        ExpressionSubscriptions.update_expression_subscription(
          existing_mute,
          %{
            subscribe: follow
          }
        )
    end

    actioned =
      case follow do
        "true" ->
          "followed"

        "false" ->
          "unfollowed"
      end

    socket =
      socket
      |> put_flash(:info, "Successfully #{actioned}.")

    socket = update_expression(socket, expression_id, user_id)

    {:noreply, socket}
  end

  defp update_expression(socket, expression_id, user_id) do
    expression =
      Expressions.get_expression!(expression_id)
      |> Expression.annotate_with_supports()
      |> Expression.annotate_with_group_data()
      |> Expression.annotate_with_linked_expressions()
      |> Expression.annotate_with_fully_supporteds_for_user(user_id)
      |> Expression.annotate_with_seeking_support(user_id)
      |> Expression.annotate_subscribed(user_id)

    supports = Supports.list_all_supports_for_expression(expression)

    seeking_supports = SeekingSupports.list_support_sought_for_expression(expression)

    linkages = ExpressionLinkages.list_expression_linkages_for_expression(expression.id)

    subscriptions =
      ExpressionSubscriptions.list_expression_subscriptions_for_expression(expression)

    fully_supporteds = FullySupporteds.list_fully_supporteds_for_expression(expression.id)

    children =
      case socket.assigns.view_all do
        true ->
          ExpressionLinkages.list_children_for_expression(expression.id)

        false ->
          ExpressionLinkages.list_supported_children_for_expression(expression.id)
      end

    children =
      children
      |> Enum.map(&Expressions.get_expression!(&1.expression_id))
      |> Expression.annotate_with_fully_supporteds_for_user(user_id)

    current_user = Accounts.get_user!(user_id)

    socket
    |> assign(:current_user_id, user_id)
    |> assign(:current_user, current_user)
    |> assign(:expression, expression)
    |> assign(:seeking_supports, seeking_supports)
    |> assign(:supports, supports)
    |> assign(:linkages, linkages)
    |> assign(:subscriptions, subscriptions)
    |> assign(:fully_supporteds, fully_supporteds)
    |> assign(:children, children)
  end
end

lib/visions_unite_web/live/fully_supported_expressions_live/index.ex
defmodule VisionsUniteWeb.FullySupportedExpressionsLive.Index do
  use VisionsUniteWeb, :live_view

  alias VisionsUnite.Expressions
  alias VisionsUnite.SeekingSupports
  alias VisionsUnite.Expressions.Expression
  alias VisionsUniteWeb.ExpressionComponent
  alias VisionsUniteWeb.NavComponent

  @impl true
  def mount(_params, session, socket) do
    user_id = session["current_user_id"]

    socket =
      socket
      |> assign(:current_user_id, user_id)

    seeking_support_from_user = SeekingSupports.list_support_sought_for_user(user_id)

    new_expressions = Expressions.list_new_expressions_for_user(user_id)

    if Enum.count(seeking_support_from_user) !== 0 or
         Enum.count(new_expressions) !== 0 do
      socket =
        socket
        |> redirect(to: "/vote")

      {:ok, socket}
    else
      {:ok, socket}
    end
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :index_important_groups, _params) do
    groups = list_vetted_groups()

    socket
    |> assign(:page_title, "Listing Important Groups")
    |> assign(:live_action, :important_groups)
    |> assign(:groups, groups)
    |> assign(:messages, [])
  end

  defp apply_action(socket, :my_subscribed_groups, _params) do
    groups = list_vetted_groups_for_user(socket.assigns.current_user_id)

    socket
    |> assign(:page_title, "Listing Subscribed Groups")
    |> assign(:live_action, :my_subscribed_groups)
    |> assign(:groups, groups)
    |> assign(:messages, [])
  end

  defp apply_action(socket, :index_important_messages, _params) do
    important_messages = list_supported_messages()

    socket
    |> assign(:page_title, "Listing Important Messages")
    |> assign(:live_action, :important_messages)
    |> assign(:groups, [])
    |> assign(:messages, important_messages)
  end

  defp apply_action(socket, :my_subscribed_messages, _params) do
    messages = list_supported_messages_for_user(socket.assigns.current_user_id)

    socket
    |> assign(:page_title, "Listing Subscribed Messages")
    |> assign(:live_action, :my_subscribed_messages)
    |> assign(:groups, [])
    |> assign(:messages, messages)
  end

  defp list_vetted_groups() do
    Expressions.list_vetted_groups()
  end

  defp list_vetted_groups_for_user(user_id) do
    Expressions.list_vetted_groups_for_user(user_id)
  end

  defp list_supported_messages() do
    Expressions.list_supported_messages()
    |> Expression.annotate_with_fully_supporteds()
  end

  defp list_supported_messages_for_user(user_id) do
    Expressions.list_supported_messages_for_user(user_id)
    |> Expression.annotate_with_fully_supporteds_for_user(user_id)
  end
end

lib/visions_unite_web/live/live_helpers.ex
defmodule VisionsUniteWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Phoenix.LiveView.JS

  @doc """
  Renders a live component inside a modal.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <.modal return_to={Routes.expression_index_path(@socket, :index)}>
        <.live_component
          module={VisionsUniteWeb.ExpressionLive.FormComponent}
          id={@expression.id || :new}
          title={@page_title}
          action={@live_action}
          return_to={Routes.expression_index_path(@socket, :index)}
          expression: @expression
        />
      </.modal>
  """
  def modal(assigns) do
    assigns = assign_new(assigns, :return_to, fn -> nil end)

    ~H"""
    <div id="modal" class="phx-modal fade-in" phx-remove={hide_modal()}>
      <div
        id="modal-content"
        class="phx-modal-content fade-in-scale"
        phx-click-away={JS.dispatch("click", to: "#close")}
        phx-window-keydown={JS.dispatch("click", to: "#close")}
        phx-key="escape"
      >
        <%= if @return_to do %>
          <%= live_patch "✖",
            to: @return_to,
            id: "close",
            class: "phx-modal-close",
            phx_click: hide_modal()
          %>
        <% else %>
          <a id="close" href="#" class="phx-modal-close" phx-click={hide_modal()}>✖</a>
        <% end %>

        <%= render_slot(@inner_block) %>
      </div>
    </div>
    """
  end

  defp hide_modal(js \\ %JS{}) do
    js
    |> JS.hide(to: "#modal", transition: "fade-out")
    |> JS.hide(to: "#modal-content", transition: "fade-out-scale")
  end
end

lib/visions_unite_web/live/nav.ex
defmodule VisionsUniteWeb.NavComponent do
  use VisionsUniteWeb, :live_view
  use Phoenix.Component

  def render(assigns) do
    nav(assigns)
  end

  def nav(assigns) do
    ~H"""
    <nav>
      <%= if @active == :important_groups do %>
        <a href="#" class="active">All Important Groups</a>
      <% else %>
        <%= link "Important Groups", to: "/important_groups" %>
      <% end %>

      <%= if @current_user_id do %>
        <%= if @active == :my_subscribed_groups do %>
          <a href="#" class="active">My Important Groups</a>
        <% else %>
          <%= link "My Important Groups", to: "/my_subscribed_groups" %>
        <% end %>
      <% end %>

      <%= if @active == :important_messages do %>
        <a href="#" class="active">All Important Messages</a>
      <% else %>
        <%= link "All Important Messages", to: "/important_messages" %>
      <% end %>

      <%= if @current_user_id do %>
        <%= if @active == :my_subscribed_messages do %>
          <a href="#" class="active">My Important Messages</a>
        <% else %>
          <%= link "My Important Messages", to: "/my_subscribed_messages" %>
        <% end %>
      <% end %>
    </nav>
    """
  end
end

lib/visions_unite_web/live/expression_show_live/show.html.heex
<%= if @live_action in [:new] do %>
  <.modal return_to={"/expression/#{@expression.id}"}>
    <.live_component
      module={VisionsUniteWeb.ExpressionLive.FormComponent}
      id={@expression.id || :new}
      title={@page_title}
      action={@live_action}
      expression={@new_expression}
      linked_expression_id={@linked_expression_id}
      linked_expression_title={@linked_expression_title}
      current_user_id={@current_user_id}
      return_to={"/expression/#{@expression.id}"}
    />
  </.modal>
<% end %>

<%= if Enum.count(@children) !== 0 and @current_user do %>
  <nav>
    <%= if @view_all do %>
      <a href="#" phx-click="view_all_toggle">View Only Fully Supported Messages</a>
      <a href="#" phx-click="view_all_toggle" class="active">View All Messages</a>
    <% else %>
      <a href="#" phx-click="view_all_toggle" class="active">View Only Fully Supported Messages</a>
      <a href="#" phx-click="view_all_toggle">View All Messages</a>
    <% end %>
  </nav>
  <br/>
<% end %>

<%= if !is_nil(@expression.parent) do %>
  <h1>
    <%= link @expression.parent.title, to: "/expression/#{@expression.parent.id}" %> / <%= @expression.title %>
  </h1>
<% else %>
  <h1>
    / <%= @expression.title %>
  </h1>
<% end %>

<p>
  <%= @expression.body %>
</p>

<%= if !@expression.seeking_support_from and @current_user do %>
  <div class="roww">
    <%= if is_nil(@expression.parent) do %>
      <%= if !@expression.subscribed do %>
        <button class="small" phx-click="set_follow" phx-value-follow={"true"} phx-value-expression_id={@expression.id}>Join Conversation</button>
      <% end %>

      <%= if @expression.subscribed do %>
        <button class="small" phx-click="set_follow" phx-value-follow={"false"} phx-value-expression_id={@expression.id}>Leave Conversation</button>
      <% end %>

      <%= live_patch to: Routes.expression_show_show_path(@socket, :new, @expression.id) do %>
        <button class="small">
          Create a new message for this group
        </button>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= if true or @current_user.super_admin do %>
  <small>
    <details>
      <summary>
        <p class="centered">_________---------========= DEBUG INFO =========---------_________</p>
      </summary>

      <%= if !is_nil(@expression.parent) do %>
        <div>
          <p>
            This expression (<%= @expression.title %>) needs support from <%= @expression.parent.quorum_count %> out of <%= @expression.parent.subscriber_count %> (sortition of <%= @expression.parent.sortition_count %>) of <%= @expression.parent.subscriber_count %> to be fully supported. Currently <%= @expression.parent.support_count %> supporting.
          </p>
        </div>
      <% end %>

      <h4>supports</h4>
      <div>
        <ul>
          <%= for support <- @supports do %>
            <li><%= "#{VisionsUnite.Accounts.get_user!(support.user_id).email}, #{support.support}, \"#{support.note}\"" %></li>
          <% end %>
        </ul>
      </div>
      <h4>sortition</h4>
      <div>
        <ul>
          <%= for seeking_support <- @seeking_supports do %>
            <li><%= "Seeking support from: #{VisionsUnite.Accounts.get_user!(seeking_support.user_id).email} for group: #{if !is_nil(seeking_support.for_group_id) do VisionsUnite.Expressions.get_expression_title(seeking_support.for_group_id) else "all" end}" %></li>
          <% end %>
        </ul>
      </div>
      <h4>linkages</h4>
      <div>
        <ul>
          <%= for link <- @linkages do %>
            <li><%= "#{VisionsUnite.Expressions.get_expression_title(link.link_id)}" %></li>
          <% end %>
        </ul>
      </div>
      <h4>subscriptions</h4>
      <div>
        <ul>
          <%= for subscription <- @subscriptions do %>
            <li><%= "#{VisionsUnite.Accounts.get_user!(subscription.user_id).email} is subscribed?: #{subscription.subscribe}" %></li>
          <% end %>
        </ul>
      </div>
      <h4>fully supporteds</h4>
      <div>
        <ul>
          <%= for fully_supported <- @fully_supporteds do %>
            <li><%= "Fully supported for the group: #{if !is_nil(fully_supported.group_id) do VisionsUnite.Expressions.get_expression_title(fully_supported.group_id) else "all" end}" %></li>
          <% end %>
        </ul>
      </div>
    </details>
  </small>
<% end %>

<%= if Enum.count(@children) !== 0 do %>
  <%= for child <- @children do %>
    <div class="boxed">
      <ExpressionComponent.expression expression={child} current_user_id={@current_user_id} />
      <%= child.body %>
    </div>
  <% end %>
<% end %>